### ISSUE TITLE
Oficial wiringpi compatibility

### ISSUE THREAD

**Issue by Aniq55** [robocomp/learnbot#8]
http://raspi.tv/how-to-install-wiringpi2-for-python-on-the-raspberry-pi#install

Follow this link for proper installation of wiringpi, the ones given don't work properly for some reason.

**Comment by mhaut** [comment]
Problems with pip package?

**Comment by Aniq55** [comment]
The commands given in the error message didn't solve my problem. But the solution in the above link did. Shall I modify the README to include the steps to installing wiringpi? @mhaut

**Comment by mhaut** [comment]
GPIO Odroid is different than Raspberry. I do not try with Raspberry. I do not know the repercussion that has to use wrappers for Raspberry in Odroid. I think when Hardkernel has made a fork it is not directly supported. Do you have some hardware to try this? @brickbit could be check this compatibility with a real robot in order to help to clarify this point.

**Comment by mhaut** [comment]
@brickbit please...
